### ISSUE TITLE
LAGT.h5  link not found

### ISSUE THREAD

**Issue by haifengxu12000** [junyongyou/lagt_vqa#1]
hello！i didn't find the link of LAGT.h5.I would be grateful if I could provide.

**Comment by junyongyou** [comment]
Hi, thanks a lot for your interest to my work. Actually the video quality model (i.e., LAGT.h5) is supposed to be trained by users on their own datasets. I provided the Phiqnet weight as it is a frame feature extractor. However, I have uploaded a LAGT.h5 file online, and you can downloaded here (https://drive.google.com/file/d/1vbycs28gPUuZhqOqlJ4_FFYNiNcFqJLF/view?usp=sharing).
